Add metadata files needed to build jdk.jfr module
ibmruntimes/openj9-openjdk-jdk21 pull request #193
Opened 2024-09-09 18:17 UTC by thallium

Backport of https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/833

2024-09-10 14:09 UTC, thallium commented
Updated metadata files.

2024-09-10 14:21 UTC, keithc-ca requested changes

2024-09-10 14:21 UTC, keithc-ca commented on src/hotspot/share/jfr/metadata/metadata.xsd
> +</xs:schema>
The version from upstream does not have the final newline: please remove it from this change.

2024-09-10 14:36 UTC, keithc-ca approved these changes

2024-09-10 14:36 UTC, merged

2024-09-18 03:01 UTC, mookey86 approved these changes