Bundle OpenJCEPlus on Mac/Linux
ibmruntimes/openj9-openjdk-jdk21 pull request #233
Opened 2024-12-04 17:00 UTC by JinhangZhang

OpenJCEPlus providers are supported on the Mac OS with aarch64 and amd64 architectures. Also on the Linux aarch64. This PR aims to add aarch64-mac, x86_64-mac and Linux aarch64 to platforms bundling OpenJCEPlus.

Backport from https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/888 & https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/896

2024-12-04 22:56 UTC, keithc-ca commented
Jenkins compile alinux,amac,osx jdk21

2024-12-05 14:37 UTC, keithc-ca requested changes
Please update the summary line of the commit to mention Linux (perhaps just copy the heading of this pull request).

2024-12-05 15:29 UTC, JinhangZhang commented
> Please update the summary line of the commit to mention Linux (perhaps just copy the heading of this pull request).

updated

2024-12-05 17:08 UTC, keithc-ca commented
For the record: successful build was https://openj9-jenkins.osuosl.org/job/PullRequest-OpenJDK21/106.

2024-12-05 17:08 UTC, merged